import classes from "./About.module.css";
import Reveal from "../components/common/Reveal";

export default function About() {
  return (
    <div className={classes.about}>
      <Reveal>
        <p>
          This project replaces my old way of tracking expenses via excel sheet.
          In addition to that, it has options to change base currency (expense's
          value remains the same) and convert currently displayed currency
          (changes values according to the currency rate from{" "}
          <a className="link" href="https://currencybeacon.com/">
            CurrencyBeacon
          </a>
          ).
        </p>
      </Reveal>
      <Reveal>
        <p>
          Another feature is displaying fundamental data on stocks in the
          "Investing" section.
        </p>
      </Reveal>
      <Reveal>
        <h2>Tech stack</h2>
      </Reveal>
      <Reveal>
        <ul>
          <li>TypeScript</li>
          <li>React</li>
          <li>HTML</li>
          <li>CSS</li>
          <li>Node.js</li>
          <li>MongoDB</li>
          <li>Tanstack Query</li>
          <li>Framer motion</li>
          <li>JSON Web Token</li>
          <li>Puppeteer</li>
        </ul>
      </Reveal>
      <Reveal>
        <h2>Optimizations</h2>
      </Reveal>
      <Reveal>
        <ul>
          <li>
            Data loading, submitting and caching is achieved via Tanstack Query.
          </li>
          <li>JWT token and its expiration are saved in local storage.</li>
          <li>Framer motion is used for the most of the animations.</li>
          <li>
            Updating currency rates happens once every 6 hours for every base
            currency (CZK, EUR, USD). The rates are saved in the database and
            after loading expenses route for the first time - the client checks
            if they are older than 6 hours, if so, they are re-fetched and
            database updated. This way the maximum number of requests is
            limited.
          </li>
          <li>
            Data scraped from{" "}
            <a className="link" href="https://currencybeacon.com/">
              Gurufocus
            </a>{" "}
            and{" "}
            <a className="link" href="https://currencybeacon.com/">
              Macrotrends
            </a>{" "}
            websites (in accordance with the terms and conditions and robots.txt
            files). Puppeteer scrapes Macrotrends twice in short window of time,
            which prompts website's human confirmation captcha on the third try.
            To avoid triggering it I have limited number of scraping attempts in
            a minute, which is tracked by a progress bar. Already searched
            stocks are stored in cache using Tanstack Query (page refresh resets
            the cache).
          </li>
        </ul>
      </Reveal>
      <Reveal>
        <h2>Lessons learned</h2>
      </Reveal>
      <Reveal>
        <ul>
          <li>
            Data loading, submitting, caching and global state management is
            achieved via Tanstack Query.
          </li>
          <li>Typescript is also great for the backend!</li>
          <li>
            Remaining currency rates could be calculated from the base currency
            rate (default displayed currency), but it seemed to me that the
            approach detailed above is more scalable (fetching rates from the
            perspective of base currency).
          </li>
          <li>
            Images on the home page are generated by Bing's Image Creator (
            <i>vector style vibrant colors dark background</i>).
          </li>
          <li>
            Limiting number of scraping requests presents a problem - not very
            user friendly interaction in case of more users.{" "}
            <ol>
              <li>
                One solution to this problem might be to change scraped website
                to a different one that does not have this limitation (although
                I have not found other website beside Macrotrends that provides
                similar data in terms of quality and quantity).
              </li>
              <li>
                Second solution might be to pay for a service subscription that
                provides required data (which I did not deem necessary due to
                the scope of this project).
              </li>
              <li>Another option would be to try to bypass the captcha.</li>
            </ol>
          </li>
        </ul>
      </Reveal>
      <Reveal>
        <h2>Check out this scroll animation</h2>
      </Reveal>
      <Reveal>
        <p>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam
          bibendum elit eget erat. Proin pede metus, vulputate nec, fermentum
          fringilla, vehicula vitae, justo. Phasellus rhoncus. Ut enim ad minim
          veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
          ea commodo consequat. Nam sed tellus id magna elementum tincidunt.
          Pellentesque habitant morbi tristique senectus et netus et malesuada
          fames ac turpis egestas. Fusce suscipit libero eget elit. Aliquam
          ornare wisi eu metus. Aliquam erat volutpat. Duis sapien nunc, commodo
          et, interdum suscipit, sollicitudin et, dolor.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Vivamus luctus egestas leo. Aenean id metus id velit ullamcorper
          pulvinar. Suspendisse nisl. Cras elementum. Nunc dapibus tortor vel mi
          dapibus sollicitudin. Maecenas sollicitudin. Nunc dapibus tortor vel
          mi dapibus sollicitudin. Phasellus et lorem id felis nonummy placerat.
          Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis
          suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Etiam
          bibendum elit eget erat. How bored are you, that you are reading this?
          Integer tempor. Integer imperdiet lectus quis justo. Maecenas
          fermentum, sem in pharetra pellentesque, velit turpis volutpat ante,
          in pharetra metus odio a lectus. Fusce dui leo, imperdiet in, aliquam
          sit amet, feugiat eu, orci. Mauris dolor felis, sagittis at, luctus
          sed, aliquam non, tellus. In enim a arcu imperdiet malesuada. Etiam
          bibendum elit eget erat.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et,
          dolor. Curabitur vitae diam non enim vestibulum interdum. Fusce dui
          leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Phasellus
          rhoncus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu,
          velit. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus
          libero, eget facilisis enim ipsum id lacus. Nulla non lectus sed nisl
          molestie malesuada. Mauris dolor felis, sagittis at, luctus sed,
          aliquam non, tellus. Aenean fermentum risus id tortor. Pellentesque
          pretium lectus id turpis. Duis sapien nunc, commodo et, interdum
          suscipit, sollicitudin et, dolor. Maecenas libero. Proin pede metus,
          vulputate nec, fermentum fringilla, vehicula vitae, justo.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Etiam posuere lacus quis dolor. Duis pulvinar. Maecenas ipsum velit,
          consectetuer eu lobortis ut, dictum at dui. Aliquam erat volutpat.
          Pellentesque pretium lectus id turpis. Vestibulum fermentum tortor id
          mi. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam.
          Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus.
          Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla,
          et sollicitudin sem purus in lacus. Mauris elementum mauris vitae
          tortor. Aliquam ornare wisi eu metus. In enim a arcu imperdiet
          malesuada. Quis autem vel eum iure reprehenderit qui in ea voluptate
          velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum
          fugiat quo voluptas nulla pariatur? Class aptent taciti sociosqu ad
          litora torquent per conubia nostra, per inceptos hymenaeos. Integer
          rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies
          odio, vitae placerat pede sem sit amet enim. Praesent vitae arcu
          tempor neque lacinia pretium. Quis autem vel eum iure reprehenderit
          qui in ea voluptate velit esse quam nihil molestiae consequatur, vel
          illum qui dolorem eum fugiat quo voluptas nulla pariatur?
        </p>
      </Reveal>
      <Reveal>
        <p>
          Aliquam in lorem sit amet leo accumsan lacinia. Quisque tincidunt
          scelerisque libero. Nunc tincidunt ante vitae massa. Aenean fermentum
          risus id tortor. Mauris dolor felis, sagittis at, luctus sed, aliquam
          non, tellus. In convallis. Sed ac dolor sit amet purus malesuada
          congue. Fusce consectetuer risus a nunc. Sed convallis magna eu sem.
          Quisque tincidunt scelerisque libero. Mauris suscipit, ligula sit amet
          pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel
          metus. Mauris dolor felis, sagittis at, luctus sed, aliquam non,
          tellus. Mauris dictum facilisis augue. Donec iaculis gravida nulla.
          Phasellus et lorem id felis nonummy placerat. Vestibulum fermentum
          tortor id mi. Curabitur bibendum justo non orci. Duis condimentum
          augue id magna semper rutrum.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam
          bibendum elit eget erat. Proin pede metus, vulputate nec, fermentum
          fringilla, vehicula vitae, justo. Phasellus rhoncus. Ut enim ad minim
          veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
          ea commodo consequat. Nam sed tellus id magna elementum tincidunt.
          Pellentesque habitant morbi tristique senectus et netus et malesuada
          fames ac turpis egestas. Fusce suscipit libero eget elit. Aliquam
          ornare wisi eu metus. Aliquam erat volutpat. Duis sapien nunc, commodo
          et, interdum suscipit, sollicitudin et, dolor.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Vivamus luctus egestas leo. Aenean id metus id velit ullamcorper
          pulvinar. Suspendisse nisl. Cras elementum. Nunc dapibus tortor vel mi
          dapibus sollicitudin. Maecenas sollicitudin. Nunc dapibus tortor vel
          mi dapibus sollicitudin. Phasellus et lorem id felis nonummy placerat.
          Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis
          suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Etiam
          bibendum elit eget erat. Integer tempor. Integer imperdiet lectus quis
          justo. Maecenas fermentum, sem in pharetra pellentesque, velit turpis
          volutpat ante, in pharetra metus odio a lectus. Fusce dui leo,
          imperdiet in, aliquam sit amet, feugiat eu, orci. Mauris dolor felis,
          sagittis at, luctus sed, aliquam non, tellus. In enim a arcu imperdiet
          malesuada. Etiam bibendum elit eget erat.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et,
          dolor. Curabitur vitae diam non enim vestibulum interdum. Fusce dui
          leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Phasellus
          rhoncus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu,
          velit. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus
          libero, eget facilisis enim ipsum id lacus. Nulla non lectus sed nisl
          molestie malesuada. Mauris dolor felis, sagittis at, luctus sed,
          aliquam non, tellus. Aenean fermentum risus id tortor. Pellentesque
          pretium lectus id turpis. Duis sapien nunc, commodo et, interdum
          suscipit, sollicitudin et, dolor. Maecenas libero. Proin pede metus,
          vulputate nec, fermentum fringilla, vehicula vitae, justo.
        </p>
      </Reveal>
      <Reveal>
        <p>
          Etiam posuere lacus quis dolor. Duis pulvinar. Maecenas ipsum velit,
          consectetuer eu lobortis ut, dictum at dui. Aliquam erat volutpat.
          Pellentesque pretium lectus id turpis. Vestibulum fermentum tortor id
          mi. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam.
          Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus.
          Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla,
          et sollicitudin sem purus in lacus. Mauris elementum mauris vitae
          tortor. Aliquam ornare wisi eu metus. In enim a arcu imperdiet
          malesuada. Quis autem vel eum iure reprehenderit qui in ea voluptate
          velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum
          fugiat quo voluptas nulla pariatur? Class aptent taciti sociosqu ad
          litora torquent per conubia nostra, per inceptos hymenaeos. Integer
          rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies
          odio, vitae placerat pede sem sit amet enim. Praesent vitae arcu
          tempor neque lacinia pretium. Quis autem vel eum iure reprehenderit
          qui in ea voluptate velit esse quam nihil molestiae consequatur, vel
          illum qui dolorem eum fugiat quo voluptas nulla pariatur?
        </p>
      </Reveal>
      <Reveal>
        <p>
          Aliquam in lorem sit amet leo accumsan lacinia. Quisque tincidunt
          scelerisque libero. Nunc tincidunt ante vitae massa. Aenean fermentum
          risus id tortor. Mauris dolor felis, sagittis at, luctus sed, aliquam
          non, tellus. In convallis. Sed ac dolor sit amet purus malesuada
          congue. Fusce consectetuer risus a nunc. Sed convallis magna eu sem.
          Quisque tincidunt scelerisque libero. Mauris suscipit, ligula sit amet
          pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel
          metus. Mauris dolor felis, sagittis at, luctus sed, aliquam non,
          tellus. Mauris dictum facilisis augue. Donec iaculis gravida nulla.
          Phasellus et lorem id felis nonummy placerat. Vestibulum fermentum
          tortor id mi. Curabitur bibendum justo non orci. Duis condimentum
          augue id magna semper rutrum.
        </p>
      </Reveal>
    </div>
  );
}
